language: php

dist: trusty

php:
  - 7.1
  - 7.0
  - 5.6
  - hhvm
  - nightly

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.* # Does not work with php below 5.5
  - SYMFONY_VERSION=4.0.*

cache:
  directories:
    - $HOME/.composer/cache

before_script:
#  - pecl install pecl_http
  - composer require --prefer-source --dev symfony/event-dispatcher:${SYMFONY_VERSION}

script: vendor/bin/phpunit -c phpunit.xml.travis -v

after_success:
  - travis_retry php vendor/bin/coveralls -v

matrix:
  exclude:
      - php: 7.0
        env: SYMFONY_VERSION=4.0.*
      - php: 5.6
        env: SYMFONY_VERSION=4.0.*
      - php: hhvm
        env: SYMFONY_VERSION=4.0.*
      - php: nightly
        env: SYMFONY_VERSION=4.0.*
  allow_failures:
#      - php: 5.3
      - php: nightly

sudo: false
